
name: Allows for the adding labels when opening a test failure issue.

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.title, 'Test failure') && !contains(github.event.issue.labels.*.name, 'needs triage') }}
    steps:
      - name: apply needs triage label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs triage
